# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('disease_name', models.CharField(max_length=50, primary_key='disease_name', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_name', models.CharField(max_length=200)),
                ('disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.disease')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='id',
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_dosage',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=50, primary_key='medicine_name', serialize=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
    ]
