# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_auto_20170725_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='medicine',
            new_name='medicine_name',
        ),
    ]
