# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20170726_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_dosage',
            field=models.IntegerField(),
        ),
    ]
